#!/usr/bin/env python3
"""Generate font_data.go: grayscale coverage atlases for ASCII 32..126.

Run once at development time; wlterm itself has no runtime dependencies.
Three cell sizes so window titles can match a range of terminal cell heights.
"""
from PIL import Image, ImageDraw, ImageFont
import sys

FONT = "/usr/share/fonts/noto/NotoSansMono-Regular.ttf"
SIZES = [(6, 12), (7, 14), (8, 16), (9, 18), (10, 20), (12, 24)]
LO, HI = 32, 126


def render(cw, ch):
    # Find the pixel size whose advance width is closest to cw.
    best = None
    for px in range(6, 40):
        f = ImageFont.truetype(FONT, px)
        adv = f.getlength("M")
        if adv <= cw and (best is None or adv > best[1]):
            best = (f, adv, px)
    f = best[0]
    asc, desc = f.getmetrics()
    # Vertically centre the ascender+descender box inside the cell.
    top = (ch - (asc + desc)) // 2
    data = bytearray()
    for c in range(LO, HI + 1):
        img = Image.new("L", (cw, ch), 0)
        d = ImageDraw.Draw(img)
        d.text((0, top), chr(c), font=f, fill=255)
        data += img.tobytes()
    return bytes(data), best[2]


out = ["package main\n\n",
       "// Code generated by tools/genfont.py. DO NOT EDIT.\n",
       "// Grayscale coverage atlases for ASCII 32..126, one byte per pixel,\n",
       "// glyphs laid out consecutively, row-major within a glyph.\n\n",
       "type fontAtlas struct {\n\tw, h int\n\tpix  string\n}\n\n",
       "var fontAtlases = []fontAtlas{\n"]
for cw, ch in SIZES:
    pix, px = render(cw, ch)
    esc = "".join("\\x%02x" % b for b in pix)
    out.append('\t{%d, %d, "%s"}, // %dpt\n' % (cw, ch, esc, px))
    print("atlas %dx%d from %dpt: %d bytes" % (cw, ch, px, len(pix)), file=sys.stderr)
out.append("}\n")
open("/home/gaurav/wlterm-experiment/font_data.go", "w").write("".join(out))
